# Generated by Django 3.2.5 on 2021-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210724_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_token',
            field=models.CharField(max_length=1000),
        ),
    ]
